### ISSUE TITLE
ProtonMail says: "This email has failed its domain's authentication requirements. It may be spoofed or improperly forwarded!"

### ISSUE THREAD

**Issue by notriddle** [emberian/this-week-in-rust#714] opened 2018-09-06 01:17 UTC
Looking at the `rust-lang.org` domain authentication setup, I saw this:

```
notriddle@desktop:~$ dig TXT rust-lang.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT rust-lang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27478
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;rust-lang.org.                 IN      TXT

;; ANSWER SECTION:
rust-lang.org.          10799   IN      TXT     "keybase-site-verification=kVWuosEqb5MkmFwpg-JvBTHmZNMPDGOVE1yWBNEBsmY"
rust-lang.org.          10799   IN      TXT     "v=spf1 a include:_hostedspf.discourse.org ~all"
rust-lang.org.          10799   IN      TXT     "v=spf1 include:servers.mcsv.net ?all"
```

Notice how there's two different SPF entries? You should merge them into one, like this:

```
rust-lang.org.          10799   IN      TXT     "keybase-site-verification=kVWuosEqb5MkmFwpg-JvBTHmZNMPDGOVE1yWBNEBsmY"
rust-lang.org.          10799   IN      TXT     "v=spf1 a include:_hostedspf.discourse.org include:servers.mcsv.net ?all"
```

For further diagnostics, try sending test messages (using the MailChimp "test email" thing that you can click while working on a campaign) to [mail-tester.com](http://mail-tester.com). They'll give you more specific diagnostics than ProtonMail does.

**Comment by ishitatsuyuki** [comment] 2018-09-06 06:48
Duplicate of #549.

**Comment by nellshamrell** [comment] 2020-08-10 16:58
Closing due to the age of this issue, but if there are any updates to it please feel free to re-open.

**Closed by nellshamrell** 2020-08-10 16:58 UTC
